src/openapi/admin/admin.yaml
src/openrpc/alchemy/_shared/components.yaml
src/openrpc/alchemy/gas-manager-coverage/gas-manager-coverage.yaml

feat: add paymaster for erc20.

---

fern/fern.config.json
package.json
pnpm-lock.yaml

This version contains hot reload for open rpc wooooo!

upgrade fern to 0.64.10

---

fern/docs.yml

fixed a redirect

---

fern/docs.yml
fern/tutorials/getting-started/alchemy-quickstart-guide.mdx

Defined in this task: https://app.asana.com/1/1129441638109975/project/1208969177908960/task/1210547124123571?focus=true

tweaks to quickstart guide

---

fern/docs.yml

sidebar restructure

---

src/openrpc/chains/solana/solana.yaml

Docs on call request: https://alchemyinsights.slack.com/archives/C03306R8XTL/p1750265852426369

Fix: Solana APIs missing example values

---

src/openapi/portfolio/portfolio.yaml

Docs on call request: https://alchemyinsights.slack.com/archives/C03306R8XTL/p1750256923856299

Remove "each" from endpoint to avoid confusion

---

fern/api-reference/introduction/api-overview.mdx

Add logos for these missing chains in docs: 
- Aptos
- Bitcoin
- Sui
- Superseed
- Anime
- Story

add missing chain logos

---

fern/api-reference/botanix/botanix-api-faq.mdx
fern/api-reference/botanix/botanix-api-quickstart.mdx
fern/api-reference/introduction/alchemy-api-reference-overview/chain-apis-overview.mdx
fern/api-reference/introduction/api-overview.mdx
fern/apis/botanix/generators.yaml
fern/docs.yml
src/openrpc/chains/botanix/botanix.yaml

Adds Botanix docs
https://app.asana.com/1/1129441638109975/project/1208969177908960/task/1210688794383088
- Adds Botanix API Quickstart
- Adds Botanix API FAQ
- Adds Botanix API specs and render those method pages
- Adds Botanix logo to homepage in Node
- Updates chain api overview page with Botanix APIs

add docs for botanix blockchain

---

fern/api-reference/data/data-api-overview.mdx
fern/api-reference/introduction/node-api-overview.mdx
fern/docs.yml

Node and Wallet sections in docs do not have a common Overview doc, adding one for each now

Add Overview section to Node and Wallet

---

fern/docs.yml

- adds global metadata for docs, og and twitter 

adds global metadata for docs

---

fern/api-reference/hyperevm/hyperevm-api-faq.mdx
fern/api-reference/hyperevm/hyperevm-api-quickstart.mdx
fern/api-reference/introduction/alchemy-api-reference-overview/chain-apis-overview.mdx
fern/api-reference/introduction/api-overview.mdx
fern/apis/hyperevm/generators.yaml
fern/docs.yml
src/openrpc/chains/hyperevm/hyperevm.yaml

self-explanatory
https://app.asana.com/1/1129441638109975/project/1208969177908960/task/1210731884065031

add hyperevm docs

---

fern/docs.yml

Add redirects for links that currently break on the marketing site for docs.

add marketing redirects

---

fern/api-reference/base/flashblocks-api-quickstart.mdx

change flashblocks support

---

fern/docs.yml

add missing redirects for aa apis

---

fern/api-reference/base/flashblocks-api-quickstart.mdx

improve base flashblocks docs

---

src/openrpc/chains/bsc/bsc.yaml

add bnb filter methods

---

fern/api-reference/pricing-resources/resources/throughput.mdx

chore: update throughput doc to reflect archv2

---

src/openapi/nft/nft.yaml

docs on call, fix spam endpoints

---

src/openrpc/alchemy/transaction-simulation/transaction-simulation.yaml
src/openrpc/alchemy/transfers/transfers.yaml

Fix endpoint examples

---

fern/api-reference/node-api/mev-protection.mdx
fern/docs.yml

Add documentation for the new MEV Protection feature, including supported networks, benefits, and technical overview.
[Asana Task: Add MEV Protection docs](https://app.asana.com/1/1129441638109975/project/1210108345639790/task/1210829842217341)
- Added `MEV Protection` documentation page under the Chain APIs section
- Described the importance of MEV protection and how it works
- Listed supported networks and key benefits

Add MEV protection docs

---

src/openrpc/chains/hyperevm/hyperevm.yaml

add hyperliquid methods

---

fern/docs.yml

revert back custom domain without www which is potentially blocking updates going to prod

---

fern/api-reference/hyperevm/hyperevm-api-quickstart.mdx

linked wallet guide to HL quickstarter

---

src/openrpc/chains/arbitrum/arbitrum.yaml

docs: adds simulatev1 to arb

---

fern/api-reference/unichain/flashblocks-api-quickstart.mdx
fern/docs.yml

adds flashblocks api quickstart for unichain

adds flashblocks api quickstart for unichain

---

src/openrpc/chains/_components/evm/methods.yaml

add eth_callMany method

---

src/openrpc/chains/_components/evm/methods.yaml

add eth_getAccount and eth_submitWork evm methods

---

fern/api-reference/websockets/subscription-api-endpoints/alchemy-minedtransactions.mdx
fern/api-reference/websockets/subscription-api-endpoints/alchemy-pendingtransactions.mdx
fern/api-reference/websockets/subscription-api-endpoints/monadlogs.mdx
fern/api-reference/websockets/subscription-api-endpoints/monadnewheads.mdx
fern/api-reference/websockets/subscription-api.mdx
fern/docs.yml

Add monadNewHeads and monadLogs subscription types to subscription API

add monadNewHeads and monadLogs types to subscription API

---

fern/api-reference/data/webhooks/custom-webhook-api-methods/read-custom-webhook-variable.mdx
fern/docs.yml
src/openapi/notify/notify.yaml

Backlog here: https://www.notion.so/alchemotion/126069f200668043bc75d8bc4789a562?v=177e11cc1ba14c1a81baf5352af6a8a6&p=126069f2006680a59a77e3a6b57943fa&pm=s

Prioritized docs fixes from Webhooks backlog

---

fern/docs.yml

add redirects for removed blast pages in docs.yml

---

fern/apis/solana-das/generators.yaml
src/openrpc/alchemy/solana-das/solana-das.yaml

Solana DAS is grouped together with NFT API so it feels more fitting to put it with Alchemy product APIs instead of Node APIs

chore: move solana-das to alchemy rpc apis

---

fern/api-reference/humanity/humanity-api-faq.mdx
fern/api-reference/humanity/humanity-api-quickstart.mdx
fern/api-reference/rise/rise-api-faq.mdx
fern/api-reference/rise/rise-api-quickstart.mdx
fern/api-reference/worldmobilechain/worldmobilechain-api-faq.mdx
fern/api-reference/worldmobilechain/worldmobilechain-api-quickstart.mdx
fern/apis/humanity/generators.yaml
fern/apis/rise/generators.yaml
fern/apis/worldmobilechain/generators.yaml
fern/docs.yml

add quickstart and faq for humanity, rise & worldmobilechain

---

fern/api-reference/fantom/fantom-deprecation-notice.mdx
fern/docs.yml

Fantom is deprecated - this PR adds a notice to inform users and redirect them to Sonic chain.

docs: add fantom deprecation notice

---

fern/api-reference/introduction/alchemy-quickstart-guide.mdx
fern/tutorials/getting-started/create-an-api-key.mdx

docs: revamp feedback mostly replacing dashboard images

docs: revamp feedback mostly replacing dashboard images

---

fern/docs.yml
fern/tutorials/build-with-ai/add-alchemy-rpc-to-any-project.mdx

Making the tutorials a bit more digestible.

Minor changes to published guides

---

fern/api-reference/op-mainnet/op-mainnet-api-faq/op-mainnet-error-codes.mdx

chore: remove url field

---

fern/docs.yml

Reordering the Build with AI section

Reorder docs section

---

src/openrpc/chains/_components/evm/methods.yaml
src/openrpc/chains/matic/matic.yaml

add missing evm method
